# Generated by Django 3.2.5 on 2021-07-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='instuments',
            new_name='instruments',
        ),
    ]
